### ISSUE TITLE
Server does not boot

### ISSUE THREAD

**Issue by Cyberunner23** [csgames/cscoins#28]
We updated our copy of the cscoins server to the most recent commit and the server does not boot.

Here are the logs:
```Generating CA Key pair
Loading wallets from Database
Creating CA Wallet
CA Wallet Id -> b0da514a8da8a0bbbc376c3e3b3c0cf973c0c50b6d3fa103ef8e53bd630ab321
Loading transactions...
No current challenge, generating a new challenge
Generating reverse_sorted_list problem nonce = 87168702
New challenge generated for 15 minutes
Traceback (most recent call last):
  File "main.py", line 12, in <module>
    ca_server.serve()
  File "/cscoins/src/caserver/CentralAuthorityServer.py", line 396, in serve
    ssl_context.load_cert_chain(self.ssl_cert)
FileNotFoundError: [Errno 2] No such file or directory
```

**Comment by jordsti** [comment]
Set ssl_on to False in ca_config.txt.

**Comment by Cyberunner23** [comment]
Works fine thanks
